-- =============================================
-- BITCOS MVP 데이터베이스 스키마 (전체)
-- Supabase DB 기준 최종 확인일: 2026-01-30
-- =============================================

-- =============================================
-- 1. 회원 관리
-- =============================================

-- users: 사용자 정보 테이블
CREATE TABLE public.users (
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    nickname TEXT NOT NULL,
    profile_image TEXT,
    role TEXT DEFAULT 'USER',                  -- 'USER' | 'ADMIN'
    allow_notif_tn CHAR(1) DEFAULT 'Y',        -- 거래 알림 허용
    allow_notif_bo CHAR(1) DEFAULT 'Y',        -- 게시판 알림 허용
    created_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,                    -- Soft Delete
    voting_coin_balance BIGINT DEFAULT 10000, -- 보팅맨 보팅코인 잔액 (기존 virtual_cash_balance에서 이름 변경)

    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_nickname_unique UNIQUE (nickname),
    CONSTRAINT users_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES auth.users(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.users IS '사용자 정보 테이블 (auth.users 연동)';
COMMENT ON COLUMN public.users.role IS 'USER: 일반회원, ADMIN: 관리자';
COMMENT ON COLUMN public.users.voting_coin_balance IS '보팅맨 보팅코인 잔액';


-- =============================================
-- 2. 커뮤니티 - 게시글
-- =============================================

-- board_posts: 게시글 테이블
CREATE TABLE public.board_posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    board_type VARCHAR NOT NULL,              -- 'free' | 'perspective'
    category VARCHAR,                          -- 'free' | 'suggestion' (자유게시판만)
    title VARCHAR NOT NULL,
    content TEXT NOT NULL,
    author_name TEXT NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    is_pinned BOOLEAN DEFAULT false,
    is_admin_post BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    
    CONSTRAINT board_posts_pkey PRIMARY KEY (post_id),
    CONSTRAINT board_posts_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_posts IS '커뮤니티 게시글 테이블';
COMMENT ON COLUMN public.board_posts.board_type IS 'free: 자유게시판, perspective: 관점게시판';
COMMENT ON COLUMN public.board_posts.category IS 'free: 자유, suggestion: 건의 (자유게시판만)';
COMMENT ON COLUMN public.board_posts.is_admin_post IS '관리자 작성 글 여부';


-- board_comments: 댓글 테이블
CREATE TABLE public.board_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    content TEXT NOT NULL,
    author_name TEXT NOT NULL,
    parent_comment_id BIGINT,                  -- 대댓글인 경우 부모 댓글 ID
    depth INTEGER NOT NULL DEFAULT 0,          -- 0: 댓글, 1: 대댓글
    like_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    
    CONSTRAINT board_comments_pkey PRIMARY KEY (comment_id),
    CONSTRAINT board_comments_post_id_fkey FOREIGN KEY (post_id) 
        REFERENCES public.board_posts(post_id) ON DELETE CASCADE,
    CONSTRAINT board_comments_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    CONSTRAINT board_comments_parent_fkey FOREIGN KEY (parent_comment_id) 
        REFERENCES public.board_comments(comment_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_comments IS '게시글 댓글 테이블';


-- board_images: 게시글 이미지 테이블
CREATE TABLE public.board_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT board_images_pkey PRIMARY KEY (image_id),
    CONSTRAINT board_images_post_id_fkey FOREIGN KEY (post_id) 
        REFERENCES public.board_posts(post_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_images IS '게시글 첨부 이미지 테이블';


-- board_post_likes: 게시글 좋아요 테이블
CREATE TABLE public.board_post_likes (
    user_id UUID NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT board_post_likes_pkey PRIMARY KEY (user_id, post_id),
    CONSTRAINT board_post_likes_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    CONSTRAINT board_post_likes_post_id_fkey FOREIGN KEY (post_id) 
        REFERENCES public.board_posts(post_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_post_likes IS '게시글 좋아요 테이블';


-- board_comment_likes: 댓글 좋아요 테이블
CREATE TABLE public.board_comment_likes (
    user_id UUID NOT NULL,
    comment_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT board_comment_likes_pkey PRIMARY KEY (user_id, comment_id),
    CONSTRAINT board_comment_likes_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    CONSTRAINT board_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) 
        REFERENCES public.board_comments(comment_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_comment_likes IS '댓글 좋아요 테이블';


-- board_bookmarks: 게시글 북마크(스크랩) 테이블
CREATE TABLE public.board_bookmarks (
    user_id UUID NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT board_bookmarks_pkey PRIMARY KEY (user_id, post_id),
    CONSTRAINT board_bookmarks_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    CONSTRAINT board_bookmarks_post_id_fkey FOREIGN KEY (post_id) 
        REFERENCES public.board_posts(post_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.board_bookmarks IS '게시글 북마크(스크랩) 테이블';


-- =============================================
-- 3. 버핏 원픽 (주식 평가)
-- =============================================

-- stocks: 주식 마스터 테이블
CREATE TABLE public.stocks (
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker VARCHAR NOT NULL,
    company_name VARCHAR NOT NULL,
    exchange VARCHAR,                          -- 거래소 (NASDAQ, NYSE 등)
    industry VARCHAR,                          -- 산업/섹터
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT stocks_pkey PRIMARY KEY (stock_id),
    CONSTRAINT stocks_ticker_unique UNIQUE (ticker)
);

COMMENT ON TABLE public.stocks IS '미국 주식 마스터 테이블';


-- index_membership: 지수 편입 이력 테이블
CREATE TABLE public.index_membership (
    stock_id BIGINT NOT NULL,
    index_code VARCHAR NOT NULL,              -- 'SP500' | 'NASDAQ100'
    effective_from DATE NOT NULL,
    effective_to DATE,                         -- NULL이면 현재 편입 중
    
    CONSTRAINT index_membership_pkey PRIMARY KEY (stock_id, index_code, effective_from),
    CONSTRAINT index_membership_stock_id_fkey FOREIGN KEY (stock_id) 
        REFERENCES public.stocks(stock_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.index_membership IS '지수 편입 이력 (S&P500, NASDAQ100)';


-- buffett_run: 버핏 평가 실행 스냅샷 테이블
CREATE TABLE public.buffett_run (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_version DATE NOT NULL,                -- 데이터 기준일
    universe VARCHAR NOT NULL,                 -- 'SP500' | 'NASDAQ100' | 'ALL'
    data_source VARCHAR NOT NULL,              -- 'yfinance' | 'fmp' 등
    
    CONSTRAINT buffett_run_pkey PRIMARY KEY (run_id)
);

COMMENT ON TABLE public.buffett_run IS '버핏 평가 실행 스냅샷';


-- buffett_result: 버핏 원픽 결과 테이블 (메인)
CREATE TABLE public.buffett_result (
    run_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    total_score NUMERIC,
    pass_status VARCHAR NOT NULL,              -- 'PASS' | 'FAIL'
    current_price NUMERIC,
    intrinsic_value NUMERIC,                   -- 적정가 (내재가치)
    gap_pct NUMERIC,                           -- 상승여력 (%)
    recommendation VARCHAR,                     -- 'BUY' | 'WAIT'
    is_undervalued BOOLEAN,
    years_data SMALLINT,                       -- 사용된 재무 데이터 연수
    trust_grade SMALLINT,                      -- 1 | 2 | 3
    trust_grade_text VARCHAR,
    trust_grade_stars VARCHAR,
    pass_reason TEXT,                          -- 우량주 통과 이유 요약문
    valuation_reason TEXT,                     -- 적정가 산정 이유 요약문
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT buffett_result_pkey PRIMARY KEY (run_id, stock_id),
    CONSTRAINT buffett_result_run_id_fkey FOREIGN KEY (run_id) 
        REFERENCES public.buffett_run(run_id) ON DELETE CASCADE,
    CONSTRAINT buffett_result_stock_id_fkey FOREIGN KEY (stock_id) 
        REFERENCES public.stocks(stock_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.buffett_result IS '버핏 평가 결과 (UI 카드/모달용)';


-- buffett_score_detail: 삭제됨 (015_drop_buffett_score_detail.sql)
-- 미사용 테이블, 코드 내 참조 없음


-- latest_price: 일간 최신 종가 테이블
CREATE TABLE public.latest_price (
    stock_id BIGINT NOT NULL,
    price_date DATE NOT NULL,
    current_price NUMERIC NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT latest_price_pkey PRIMARY KEY (stock_id),
    CONSTRAINT latest_price_stock_id_fkey FOREIGN KEY (stock_id) 
        REFERENCES public.stocks(stock_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.latest_price IS '일간 최신 종가 저장';


-- =============================================
-- 4. 모의 선물 거래
-- =============================================

-- simulation_accounts: 모의 거래 계좌 테이블
CREATE TABLE public.simulation_accounts (
    user_id UUID NOT NULL,
    cash_balance NUMERIC NOT NULL DEFAULT 10000.00,  -- 현금 잔고 (USDT)
    total_asset NUMERIC NOT NULL DEFAULT 10000.00,   -- 총 자산 (현금 + 포지션 가치)
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    
    CONSTRAINT simulation_accounts_pkey PRIMARY KEY (user_id),
    CONSTRAINT simulation_accounts_user_id_fkey FOREIGN KEY (user_id) 
        REFERENCES public.users(user_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.simulation_accounts IS '모의 선물 거래 계좌';


-- =============================================
-- 5. 인덱스 (성능 최적화)
-- =============================================

-- 커뮤니티
CREATE INDEX idx_board_posts_user ON public.board_posts(user_id);
CREATE INDEX idx_board_posts_board_type ON public.board_posts(board_type);
CREATE INDEX idx_board_posts_created_at ON public.board_posts(created_at DESC);
CREATE INDEX idx_board_comments_post ON public.board_comments(post_id);
CREATE INDEX idx_board_images_post ON public.board_images(post_id);

-- 버핏 원픽
CREATE INDEX idx_buffett_result_pass ON public.buffett_result(run_id, pass_status);
CREATE INDEX idx_buffett_result_undervalued ON public.buffett_result(run_id, is_undervalued);
CREATE INDEX idx_buffett_result_gap ON public.buffett_result(run_id, gap_pct DESC);
CREATE INDEX idx_index_membership_code ON public.index_membership(index_code, effective_to);


-- =============================================
-- 테이블 요약 (13개)
-- =============================================
/*
┌─────────────────────────────────────────────────────────────────────────┐
│  1. 회원관리 (1개)                                                       │
│     └── users                                                           │
├─────────────────────────────────────────────────────────────────────────┤
│  2. 커뮤니티 (6개)                                                       │
│     ├── board_posts          게시글                                     │
│     ├── board_comments       댓글                                       │
│     ├── board_images         첨부 이미지                                │
│     ├── board_post_likes     게시글 좋아요                              │
│     ├── board_comment_likes  댓글 좋아요                                │
│     └── board_bookmarks      북마크(스크랩)                             │
├─────────────────────────────────────────────────────────────────────────┤
│  3. 버핏 원픽 (4개)                                                      │
│     ├── stocks               주식 마스터                                │
│     ├── index_membership     지수 편입 이력                             │
│     ├── buffett_run          평가 실행 스냅샷                           │
│     ├── buffett_result       평가 결과                                  │
│     └── latest_price         최신 종가                                  │
├─────────────────────────────────────────────────────────────────────────┤
│  4. 모의 거래 (1개)                                                      │
│     └── simulation_accounts  모의 거래 계좌                             │
└─────────────────────────────────────────────────────────────────────────┘

테이블 관계도 (ERD):

    auth.users ──┬──► users ◄──┬── board_posts ◄── board_images
                 │             │        │
                 │             │        ├── board_comments
                 │             │        │        │
                 │             ├────────┼────────┴── board_comment_likes
                 │             ├────────┴─────────── board_post_likes
                 │             └──────────────────── board_bookmarks
                 │
                 └──► simulation_accounts

    stocks ──┬── index_membership
             ├── latest_price
             └── buffett_result ◄── buffett_run
*/
