-- =============================================
-- 013: page_views — 오늘 페이지뷰 집계용
-- 관리자 대시보드에서 일별 페이지뷰 수 집계
-- =============================================

CREATE TABLE IF NOT EXISTS public.page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path TEXT NOT NULL,
    user_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT page_views_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON public.page_views(created_at);
CREATE INDEX IF NOT EXISTS idx_page_views_user_id ON public.page_views(user_id) WHERE user_id IS NOT NULL;

COMMENT ON TABLE public.page_views IS '페이지뷰 로그 (관리자 대시보드 집계용)';
